[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0x5c59cda79966bf9d63ba2a0a752870d82dfbc0ef28f873f4ac8108f7291770c6'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]